# Generated by Django 4.2.6 on 2023-10-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('businessentityid', models.IntegerField(primary_key=True, serialize=False)),
                ('nationalidnumber', models.CharField(max_length=15)),
                ('loginid', models.CharField(max_length=256)),
                ('jobtitle', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('maritalstatus', models.CharField(max_length=1)),
                ('gender', models.CharField(max_length=1)),
                ('hiredate', models.DateField()),
                ('salariedflag', models.BooleanField(default=True)),
                ('vacationhours', models.SmallIntegerField(default=0)),
                ('sickleavehours', models.SmallIntegerField(default=0)),
                ('currentflag', models.BooleanField(default=True)),
                ('rowguid', models.UUIDField()),
                ('modifieddate', models.DateTimeField(auto_now=True)),
                ('organizationnode', models.CharField(default='/', max_length=255)),
            ],
            options={
                'db_table': 'humanresources.employee',
                'managed': False,
            },
        ),
    ]
